name: deploy
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    name: deploy
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: jdk 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: gradle caching
        uses: gradle/gradle-build-action@v2
      - run: git fetch origin main
      - name: publish all
        run: ./gradlew changelogPush -Prelease=true -Penable_publishing=true --stacktrace --warning-mode all
      - run: git checkout main
      - run: git merge release --ff-only
      - run: git push origin main